### ISSUE TITLE
 I can not run your demo code

### ISSUE THREAD

**Issue by su-action** [laike9m/Cyberbrain-Deprecated#12]
```python
Traceback (most recent call last):
  File "/python3.8/site-packages/cyberbrain/api.py", line 48, in local_tracer
    computation_manager.add_computation(event_type, frame, arg)
  File "/python3.8/site-packages/cyberbrain/computation.py", line 159, in add_computation
    comp = Line(
  File "/python3.8/site-packages/cyberbrain/computation.py", line 49, in __init__
    self.code_str, mode=black.FileMode()
TypeError: __call__() missing 1 required positional argument: 'value'
```

**Comment by laike9m** [comment]
Hi, which black version are you using?

**Comment by sdl0day** [comment]
> Hi, which black version are you using?

My environment are as follows: 
1.Mac 10.14
2.I use miniconda3 to create a virtual python environment,the python version is 3.8.0. Then I use pip (pip in this virtual env) install cyberbrain version is 0.0.0.2,graphviz version is  0.11.1,poetry version is 1.0.0.
